### ISSUE TITLE
janis run incorrect error message.

### ISSUE THREAD

**Issue by drtconway** [PMCC-BioinformaticsCore/janis-assistant#27]
Consider the following definitions:

```
# more hammer.py 
from typing import Dict, Optional, List, Any
from janis_core import PythonTool, Workflow, TOutput
from janis_core import Array, String

class Trivial(PythonTool):
    @staticmethod
    def code_block(mean: int) -> Dict[str, Any]:
        import math
        import random

        x = random.gammavariate(mean)

        res = str(x)

        return { "out": res }

    def outputs(self) -> List[TOutput]:
        return [TOutput("out", String)]

    def id(self) -> str:
        return "Trivial"

class Sha256(PythonTool):
    @staticmethod
    def code_block(things: List[str]) -> Dict[str, Any]:
        import hashlib

        md = hashlib.new('sha256')
        for thing in things:
            md.update(thing.encode('utf-8'))

        return { "out": str(md.hexdigest()) }

    def outputs(self) -> List[TOutput]:
        return [TOutput("out", str)]

    def id(self) -> str:
        return "Sha256"

    def version(self):
        return "v0.1.0"
```

Invoking `janis run` on `Sha256` works just fine:
```
$ janis run -o foo --name Sha256 hammer.py --things the quick brown fox
2020-06-01T22:41:49 [INFO]: Starting task with id = 'f9a7d3'
f9a7d3
2020-06-01T22:41:49 [INFO]: Exporting tool files to '/foo/janis/workflow/original'
2020-06-01T22:41:49 [INFO]: Zipping tools
2020-06-01T22:41:49 [INFO]: Zipped tools
2020-06-01T22:41:49 [INFO]: Saved workflow with id 'Sha256' to '/foo/janis/workflow'
2020-06-01T22:41:49 [INFO]: Exporting tool files to '/foo/janis/workflow'
2020-06-01T22:41:49 [INFO]: Zipping tools
2020-06-01T22:41:49 [INFO]: Zipped tools
2020-06-01T22:41:49 [INFO]: Status changed to: Queued
2020-06-01T22:41:49 [INFO]: Starting cromwell (cromwell-50.jar)...
2020-06-01T22:41:49 [INFO]: Cromwell is starting with pid=26
2020-06-01T22:41:49 [INFO]: Will log to file
2020-06-01T22:43:23 [INFO]: Service successfully started with pid=26
2020-06-01T22:43:23 [INFO]: Submitted workflow (f9a7d3), got engine id = '4c089495-9a98-44f9-9ae3-b9940d3280d1'
2020-06-01T22:43:35 [INFO]: Status changed to: Running
2020-06-01T22:43:41 [INFO]: Status changed to: Completed
2020-06-01T22:43:41 [INFO]: Task has finished with status: Completed
2020-06-01T22:43:41 [INFO]: Hard linking /foo/janis/execution/Sha256/4c089495-9a98-44f9-9ae3-b9940d3280d1/call-Sha256/execution/stdout → /foo/janis/logs/_stdout
2020-06-01T22:43:41 [INFO]: Hard linking /foo/janis/execution/Sha256/4c089495-9a98-44f9-9ae3-b9940d3280d1/call-Sha256/execution/stderr → /foo/janis/logs/_stderr
2020-06-01T22:43:41 [INFO]: View the task outputs: file:///foo
2020-06-01T22:43:41 [INFO]: Cleaning up execution directory
2020-06-01T22:43:41 [INFO]: Removing local directory '/foo/janis/execution'
2020-06-01T22:43:41 [INFO]: Stopping cromwell
2020-06-01T22:43:41 [INFO]: Stopped cromwell
2020-06-01T22:43:41 [INFO]: Finished managing task 'f9a7d3'.
2020-06-01T22:43:41 [INFO]: Exiting
$ 
```

But invoking `janis run` on `Trivial` not only doesn't work, but gives a misleading error message:

```
$ janis run -o foo --name Trivial hammer.py --mean 10                   
Traceback (most recent call last):
  File "/usr/local/bin/janis", line 11, in <module>
    load_entry_point('janis-pipelines.runner==0.9.17', 'console_scripts', 'janis')()
  File "/usr/local/lib/python3.8/dist-packages/janis_pipelines.runner-0.9.17-py3.8.egg/janis_assistant/cli.py", line 153, in process_args
  File "/usr/local/lib/python3.8/dist-packages/janis_pipelines.runner-0.9.17-py3.8.egg/janis_assistant/cli.py", line 792, in do_run
  File "/usr/local/lib/python3.8/dist-packages/janis_pipelines.runner-0.9.17-py3.8.egg/janis_assistant/main.py", line 403, in fromjanis
Exception: Couldn't find workflow with name: hammer.py
$ 
```

It appears `janis translate` has exactly the same problem.

**Comment by drtconway** [comment]
Ah. In a different context, I discovered that the `Trivial` class was missing the abstract method `version`. I haven't rerun the exact test case, but I assume it will get things going, though it would be good to get that error message from the above case.

**Comment by illusional** [comment]
Hey @drtconway, this is a good one! There's good reasons why we skip abstract classes when looking for tools within files (because often you might have a base that you're building onto) - it's a similar problem to how when we populate the toolbox we skip abstract classes, even though it might be frustrating when you're adding new tools and it's just not showing up.

You can see the original code here: https://github.com/PMCC-BioinformaticsCore/janis-assistant/blob/fea79a878e06f111f353da223ec7f3f636999c47/janis_assistant/utils/pathhelper.py#L165-L194

I've made a change to more quickly catch tools in files if the name file is specified (https://github.com/PMCC-BioinformaticsCore/janis-assistant/pull/28). Now that this has been merged, with respect to your original file:


```sh
# will translate the Sha256 tool because it's the only nonabstract tool in the file
janis translate hammer.py wdl

# Will fail with the error: Can't instantiate abstract class Trivial with abstract methods version
janis translate --name Trivial hammer.py wdl
```
Hopefully this resolves the problem you're having, I'll close this ticket and you can reopen if this fix doesn't solve your problem.
